artifacts-menu:
  title: "Your Artifacts"
  rows: 5
  slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 30, 32 ] # should be 20
  items:
    artifact: # automaterial; {artifact}
      name: "&6&l{artifact}"
    back:
      material: ARROW
      name: "&6&lBack"
      lore:
        - "&7Go back to the &eMain Menu"
      slot: 36
    undiscovered: # automaterial; {artifact}
      material: BRICK
      name: "&c&l???"
      lore:
        - "&7You have not found this artifact"
    custom:
      background:
        material: "BLACK_STAINED_GLASS_PANE"
        name: "&a"
        fill: true

clutch-levels:
  1: "0.0,0.0,0.0,0.0,0.0"
  2: "0.0,0.0,0.0,0.0,0.0"
  3: "0.0,0.0,0.0,0.0,0.0"

# worlds and their teleport y levels
fall-teleport:
  world: -100.0

main-menu:
  title: "Your Stuff"
  rows: 3
  items:
    artifacts:
      material: BREWER_POTTERY_SHERD
      name: "&6&lArtifacts"
      slot: 11
    pets:
      hdb: 67567
      name: "&6&lPets"
      slot: 15
    custom:
      background:
        material: BLACK_STAINED_GLASS_PANE
        name: "&a"
        fill: true

menu-item:
  material: NETHER_STAR
  name: "&6&lMain Menu"
  lore:
    - "&a&lRight-Click &7to open the Main Menu"

messages:
  artifact-find: # {artifact}
    - "&aYou found the &6{artifact} &aartifact!"
  artifact-duplicate: # {artifact}
    - "&cYou have already found the {artifact} artifact!"
  artifact-talk-to-archaeologist:
    - "&6Talk to the archaeologist about this artifact."

player-items:
  sapphire:
    material: LAPIS_LAZULI
    name: "&6&lRare Sapphire"
  travel-orb:
    material: ENDER_EYE
    name: "&6&lTravel Orb"
    lore:
      - "&7Use in &eEnd Portal Frames &7to"
      - "&7instantly travel between them"

reader:
  enabled: false
  file-path: ""

spawn-location:
  enabled: false
  location: "world,0.0,100.0,0.0,0.0,0.0"

velocity-blocks:
  "0,0,0": "0.0,0.0,0.0"