artifacts-menu:
  title: "Your Artifacts"
  rows: 5
  slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 30, 32 ] # should be 20
  items:
    artifact: # automaterial; {artifact}
      name: "&6&l{artifact}"
    back:
      material: ARROW
      name: "&6&lBack"
      lore:
        - "&7Go back to the &eMain Menu"
      slot: 36
    undiscovered: # automaterial; {artifact}
      material: BRICK
      name: "&c&l???"
      lore:
        - "&7You have not found this artifact"
    custom:
      background:
        material: "BLACK_STAINED_GLASS_PANE"
        name: "&a"
        fill: true

block-replace:
  enabled: false
  location: "world,0,0,0"
  material: ICE
  time: 1200

clutch-levels:
  1: "0.0,0.0,0.0,0.0,0.0"
  2: "0.0,0.0,0.0,0.0,0.0"
  3: "0.0,0.0,0.0,0.0,0.0"

# worlds and their teleport y levels
fall-teleport:
  world: -100.0

inventory-items:
  extra-lore:
    amount: # {amount}
      - "&e&lx{amount}"
    equip:
      - "&a&lClick &7to equip"
    unequip:
      - "&a&lClick &7to unequip"
  four-corners-tnt-buff:
    material: TNT
    name: "&6&l4 Corners TNT Buff"
    lore:
      - "&7Use to buff the &e4 Corners"
      - "&7minigame by spawning TNT."
  four-corners-mobs-buff:
    material: ZOMBIE_HEAD
    name: "&6&l4 Corners Mobs Buff"
    lore:
      - "&7Use to buff the &e4 Corners"
      - "&7minigame by spawning monsters."
  highblock-buff:
    material: INK_SAC
    name: "&6&lPharaoh's Curse Buff"
    lore:
      - "&7Use to buff &eThe Pharaoh's Curse"
      - "&7minigame by making blocks fall faster."
  sapphire:
    material: LAPIS_LAZULI
    name: "&6&lRare Sapphire"
    lore:
      - "&7A very rare artifact."
  speed-boost:
    material: POTION
    name: "&6&lSpeed Boost"
    lore:
      - "&7Gives you a 5 minute speed boost."
  travel-orb:
    material: ENDER_EYE
    name: "&6&lTravel Orb"
    lore:
      - "&7Use in &eEnd Portal Frames &7to"
      - "&7instantly travel between them."

# exclude: list of player UUIDs
leaderboards:
  format: "&6{pos}. &e{player} &7- &e{score}" # {player} {pos} {score}
  per-page: 10
  leaderboards:
    donations:
      location: "world,0.0,0.0,0.0"
      title: "Top Donors"
      exclude: [ ]
    hidden-path:
      location: "world,0.0,0.0,0.0"
      title: "Hidden Path Quickest Times"
      exclude: [ ]
    playtime:
      location: "world,0.0,0.0,0.0"
      title: "Total Playtime"
      exclude: [ ]
    race:
      location: "world,0.0,0.0,0.0"
      title: "Race Times"
      exclude: [ ]
    race-lap:
      location: "world,0.0,0.0,0.0"
      title: "Race Laps"
      exclude: [ ]

main-menu:
  title: "Your Stuff"
  rows: 3
  items:
    artifacts:
      material: BREWER_POTTERY_SHERD
      name: "&6&lArtifacts"
      slot: 11
    pets:
      hdb: 67567
      name: "&6&lPets"
      slot: 15
    custom:
      background:
        material: BLACK_STAINED_GLASS_PANE
        name: "&a"
        fill: true

menu-item:
  material: NETHER_STAR
  name: "&6&lMain Menu"
  lore:
    - "&a&lRight-Click &7to open the Main Menu"

messages:
  artifact-find: # {artifact}
    - "&aYou found the &6{artifact} &aartifact!"
  artifact-duplicate: # {artifact}
    - "&cYou have already found the {artifact} artifact!"
  artifact-talk-to-archaeologist:
    - "&6Talk to the archaeologist about this artifact."
  hidden-path-end:
    - "&cYour game has been reset because you left the region."
  hidden-path-finish: # {personal_best} {time}
    - "&aComplete! Your time was &6{time}&a. Your personal best is &6{personal_best}&a."
  hidden-path-finish-pb: # {previous_personal_best} {time}
    - "&aComplete! You achieved a new personal best of &6{time}&a. Your previous personal best was &6{previous_personal_best}&a."
  hidden-path-start:
    - "&aYour time has started! Find the correct path and press the button in the middle."
  speed-boost-activate:
    - "&aActivated speed boost for &65 minutes&a."
  speed-boost-already-active:
    - "&cYou already have a speed boost active!"
  speed-boost-expire:
    - "&6Your speed boost has run out."

reader:
  enabled: false
  file-path: ""

spawn-location:
  enabled: false
  location: "world,0.0,100.0,0.0,0.0,0.0"

speed-boost:
  activate-sound:
    enabled: true
    sound: "BLOCK_BREWING_STAND_BREW,1.2"
  duration: 300 # seconds
  speed: 0.3 # 0.0 - 1.0

travel-frames:
  "world,0,0,0": "world,0.0,0.0,0.0,0.0,0.0"

velocity-blocks:
  "0,0,0": "0.0,0.0,0.0"